export type VehicleCategoryId = 'car' | 'two_wheeler' | 'other'

export type VehicleStatus = 'active' | 'sold' | 'inactive'

export type VehicleAttentionSeverity = 'high' | 'medium' | 'low'

export type VehicleTimelineEventType =
	| 'vehicle_purchased'
	| 'registration_issued'
	| 'insurance_started'
	| 'insurance_renewed'
	| 'puc_renewed'
	| 'service_completed'
	| 'warranty_started'
	| 'warranty_expiring'
	| 'document_added'

export type VehicleFactKey =
	| 'registration_number'
	| 'registration_date'
	| 'owner'
	| 'make'
	| 'model'
	| 'variant'
	| 'fuel_type'
	| 'color'
	| 'insurance_provider'
	| 'policy_number'
	| 'policy_start'
	| 'policy_expiry'
	| 'idv'
	| 'premium'
	| 'puc_certificate_number'
	| 'puc_expiry'
	| 'warranty_provider'
	| 'warranty_expiry'
	| 'service_date'
	| 'service_mileage'
	| 'service_amount'
	| 'service_center'
	| 'service_type'
	| 'next_service_date'
	| 'next_service_mileage'
	| 'lender'
	| 'agreement_number'
	| 'financed_amount'
	| 'monthly_payment'
	| 'tenure'
	| 'outstanding_amount'
	| 'vin'
	| 'engine_number'
	| 'purchase_date'
