import type { MetricDefinition } from '@/features/health/domain/metric.types'

export const METRIC_DEFINITIONS: MetricDefinition[] = [
	{
		canonicalId: 'hba1c',
		displayName: 'HbA1c',
		aliases: [
			'hba1c',
			'hb a1c',
			'glycated hemoglobin',
			'glycated haemoglobin',
			'a1c',
		],
		category: 'diabetes',
		defaultUnit: '%',
	},
	{
		canonicalId: 'vitamin-d',
		displayName: 'Vitamin D',
		aliases: ['vitamin d', '25-oh vitamin d', '25 hydroxy vitamin d', 'vit d'],
		category: 'vitamin',
		defaultUnit: 'ng/mL',
	},
	{
		canonicalId: 'vitamin-b12',
		displayName: 'Vitamin B12',
		aliases: ['vitamin b12', 'b12', 'cobalamin'],
		category: 'vitamin',
		defaultUnit: 'pg/mL',
	},
	{
		canonicalId: 'hemoglobin',
		displayName: 'Hemoglobin',
		aliases: ['hemoglobin', 'haemoglobin', 'hb'],
		category: 'blood-count',
		defaultUnit: 'g/dL',
	},
	{
		canonicalId: 'platelet-count',
		displayName: 'Platelet Count',
		aliases: ['platelet count', 'platelets', 'plt'],
		category: 'blood-count',
		defaultUnit: '/µL',
	},
	{
		canonicalId: 'wbc',
		displayName: 'WBC Count',
		aliases: ['wbc count', 'wbc', 'white blood cell', 'leukocyte'],
		category: 'blood-count',
		defaultUnit: '/µL',
	},
	{
		canonicalId: 'creatinine',
		displayName: 'Creatinine',
		aliases: ['creatinine', 'serum creatinine'],
		category: 'kidney',
		defaultUnit: 'mg/dL',
	},
	{
		canonicalId: 'egfr',
		displayName: 'eGFR',
		aliases: ['egfr', 'gfr', 'estimated gfr'],
		category: 'kidney',
		defaultUnit: 'mL/min',
	},
	{
		canonicalId: 'alt',
		displayName: 'ALT (SGPT)',
		aliases: ['alt', 'sgpt', 'alanine aminotransferase', 'alt (sgpt)'],
		category: 'liver',
		defaultUnit: 'U/L',
	},
	{
		canonicalId: 'ast',
		displayName: 'AST (SGOT)',
		aliases: ['ast', 'sgot', 'aspartate aminotransferase', 'ast (sgot)'],
		category: 'liver',
		defaultUnit: 'U/L',
	},
	{
		canonicalId: 'ggt',
		displayName: 'GGT',
		aliases: ['ggt', 'gamma gt', 'gamma glutamyl transferase'],
		category: 'liver',
		defaultUnit: 'U/L',
	},
	{
		canonicalId: 'hdl',
		displayName: 'HDL Cholesterol',
		aliases: ['hdl', 'hdl cholesterol'],
		category: 'heart',
		defaultUnit: 'mg/dL',
	},
	{
		canonicalId: 'ldl',
		displayName: 'LDL Cholesterol',
		aliases: ['ldl', 'ldl cholesterol'],
		category: 'heart',
		defaultUnit: 'mg/dL',
	},
	{
		canonicalId: 'triglycerides',
		displayName: 'Triglycerides',
		aliases: ['triglycerides', 'triglyceride', 'tg'],
		category: 'heart',
		defaultUnit: 'mg/dL',
	},
	{
		canonicalId: 'total-cholesterol',
		displayName: 'Total Cholesterol',
		aliases: ['total cholesterol', 'cholesterol total', 'cholesterol'],
		category: 'heart',
		defaultUnit: 'mg/dL',
	},
	{
		canonicalId: 'tsh',
		displayName: 'TSH',
		aliases: ['tsh', 'thyroid stimulating hormone'],
		category: 'thyroid',
		defaultUnit: 'µIU/mL',
	},
	{
		canonicalId: 't3',
		displayName: 'T3',
		aliases: ['t3', 'triiodothyronine', 'free t3'],
		category: 'thyroid',
		defaultUnit: 'pg/mL',
	},
	{
		canonicalId: 't4',
		displayName: 'T4',
		aliases: ['t4', 'thyroxine', 'free t4'],
		category: 'thyroid',
		defaultUnit: 'ng/dL',
	},
	{
		canonicalId: 'calcium',
		displayName: 'Calcium',
		aliases: ['calcium', 'serum calcium'],
		category: 'general',
		defaultUnit: 'mg/dL',
	},
	{
		canonicalId: 'uric-acid',
		displayName: 'Uric Acid',
		aliases: ['uric acid'],
		category: 'general',
		defaultUnit: 'mg/dL',
	},
	{
		canonicalId: 'fasting-glucose',
		displayName: 'Fasting Glucose',
		aliases: [
			'fasting glucose',
			'blood sugar',
			'glucose fasting',
			'fasting blood sugar',
			'fbs',
		],
		category: 'diabetes',
		defaultUnit: 'mg/dL',
	},
	{
		canonicalId: 'bilirubin',
		displayName: 'Bilirubin Total',
		aliases: ['bilirubin total', 'total bilirubin', 'bilirubin'],
		category: 'liver',
		defaultUnit: 'mg/dL',
	},
	{
		canonicalId: 'albumin',
		displayName: 'Albumin',
		aliases: ['albumin', 'serum albumin'],
		category: 'liver',
		defaultUnit: 'g/dL',
	},
	{
		canonicalId: 'folate',
		displayName: 'Folate',
		aliases: ['folate', 'folic acid'],
		category: 'vitamin',
		defaultUnit: 'ng/mL',
	},
	{
		canonicalId: 'iron',
		displayName: 'Iron',
		aliases: ['iron', 'serum iron'],
		category: 'vitamin',
		defaultUnit: 'µg/dL',
	},
	{
		canonicalId: 'uibc',
		displayName: 'UIBC',
		aliases: [
			'uibc',
			'unsat iron binding capacity',
			'unsat.iron-binding capacity',
		],
		category: 'vitamin',
		defaultUnit: 'µg/dL',
	},
	{
		canonicalId: 'tibc',
		displayName: 'Total Iron Binding Capacity',
		aliases: ['tibc', 'total iron binding capacity'],
		category: 'vitamin',
		defaultUnit: 'µg/dL',
	},
	{
		canonicalId: 'iron-saturation',
		displayName: 'Iron Saturation',
		aliases: ['iron saturation', 'transferrin saturation'],
		category: 'vitamin',
		defaultUnit: '%',
	},
	{
		canonicalId: 'ferritin',
		displayName: 'Ferritin',
		aliases: ['ferritin', 'serum ferritin'],
		category: 'vitamin',
		defaultUnit: 'ng/mL',
	},
	{
		canonicalId: 'sodium',
		displayName: 'Sodium',
		aliases: ['sodium', 'serum sodium', 'na'],
		category: 'general',
		defaultUnit: 'mmol/L',
	},
	{
		canonicalId: 'potassium',
		displayName: 'Potassium',
		aliases: ['potassium', 'serum potassium', 'k'],
		category: 'general',
		defaultUnit: 'mmol/L',
	},
	{
		canonicalId: 'chloride',
		displayName: 'Chloride',
		aliases: ['chloride', 'serum chloride', 'cl'],
		category: 'general',
		defaultUnit: 'mmol/L',
	},
	{
		canonicalId: 'cea',
		displayName: 'CEA',
		aliases: ['cea', 'carcino embryonic antigen', 'carcinoembryonic antigen'],
		category: 'general',
		defaultUnit: 'ng/mL',
	},
]
