import { C } from '@/constants/colors'
import type { EmailItem, MailFilter } from '@/types'

export const MAIL_COPY = {
	title: 'Mail',
	unreadLabel: '12 unread',
	searchPlaceholder: 'Search mail...',
} as const

export const mailFilters: MailFilter[] = [
	'All',
	'Critical',
	'Reply',
	'Finance',
	'Travel',
]

export const emails: EmailItem[] = [
	{
		initials: 'PS',
		bg: '#7C4DFF',
		name: 'Priya Sharma',
		unread: true,
		time: '10:23 AM',
		subject: 'RE: Series A pitch deck feedback',
		preview: 'Needs review of unit economics + call by Friday.',
		ai: 'Reply needed · call by Friday',
		aiColor: C.red,
		score: 95,
		category: 'Reply',
		tag: 'Reply',
	},
	{
		initials: 'HB',
		bg: '#E53935',
		name: 'HDFC Bank',
		unread: true,
		time: '8:00 AM',
		subject: 'Credit Card Payment Due — ₹24,800',
		preview: 'Due tomorrow. Avoid ₹950 late fee.',
		ai: 'Pay ₹24,800 before 5 PM tomorrow',
		aiColor: C.red,
		score: 99,
		category: 'Critical',
		tag: 'Critical',
	},
	{
		initials: 'AB',
		bg: '#F4511E',
		name: 'Airbnb',
		unread: false,
		time: 'Yesterday',
		subject: 'Your Paris reservation confirmed ✓',
		preview: 'Aug 14–19 · CitizenM Gare de Lyon.',
		ai: 'Hotel confirmed · saved to Travel',
		aiColor: C.teal,
		score: 60,
		category: 'Travel',
		tag: 'Travel',
	},
	{
		initials: 'RM',
		bg: '#00897B',
		name: 'Rohan Mehta',
		unread: true,
		time: 'Yesterday',
		subject: 'Project proposal — review before Monday?',
		preview: 'Revised. Budget ₹2.4 Cr over 18 months.',
		ai: 'Review proposal · reply by Monday',
		aiColor: C.orange,
		score: 78,
		category: 'Reply',
		tag: 'Reply',
	},
	{
		initials: 'ZR',
		bg: '#3949AB',
		name: 'Zerodha',
		unread: false,
		time: 'Mon',
		subject: 'Portfolio summary — July 2026',
		preview: 'Your holdings gained 3.2% this week.',
		ai: 'No action needed',
		aiColor: C.textMuted,
		score: 30,
		category: 'Finance',
		tag: 'Finance',
	},
]
