export type {
	OcrDocumentMetadata,
	OcrDocumentResult,
	OcrExtractionResult,
	OcrPage,
	OcrTable,
	OcrTableCell,
	OcrErrorCode,
	DocumentOCRProvider,
	DocumentOCRService,
	OcrDocumentInput,
	RunOcrWithRetryOptions,
	RunOcrWithRetryResult,
	OcrProviderType,
	OcrProviderFactoryOptions,
	GoogleDocumentAiProviderOptions,
	MockLabMetricRow,
	MockLabTemplate,
} from '../../../../packages/core/ocr/src/index.ts'
export {
	toLegacyOcrResult,
	getOcrErrorMessage,
	OcrProviderError,
	MockOCRProvider,
	mockOCRProvider,
	MockDocumentOCRService,
	mockDocumentOCRService,
	buildMockOcrDocumentResult,
	MOCK_LAB_TEMPLATES,
	GoogleDocumentAIProvider,
	OCR_SETUP_MESSAGE,
	AzureDocumentIntelligenceProvider,
	azureDocumentIntelligenceProvider,
	runOcrWithRetry,
	documentProcessingConfig,
	isProductionOcrProvider,
	ocrStorageConfig,
} from '../../../../packages/core/ocr/src/index.ts'
export {
	createOCRProvider,
	defaultOCRProvider,
} from '@/features/document-intelligence/ocr/ocr-provider.factory'
